# ─── App ──────────────────
spring.application.name=identityCore
server.port=8080

# ─── Database profile ──────────────────
spring.profiles.active=postgres

# ─── SQL Init (seed data) ──────────────────
spring.sql.init.mode=embedded
spring.jpa.defer-datasource-initialization=true

# ─── Session ──────────────────
server.servlet.session.timeout=600s

# ─── Thymeleaf ──────────────────
spring.thymeleaf.cache=false

# ─── Logging ──────────────────
logging.level.root=WARN
logging.level.dev.tharbytes=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/application.log

# ─── OAuth2 ──────────────────

spring.security.oauth2.client.registration.google.client-id= 742087726024-94nsglsgbo4j5hc3adc8h94jdffm31j1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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

spring.security.oauth2.client.registration.github.client-id= Ov23liYpMO0Zshix3Uvd
spring.security.oauth2.client.registration.github.client-secret= 448f873c9ae23d39681d7f571f3cd45d515e3509
spring.security.oauth2.client.registration.github.scope=read:user,user:email
