# ─── App ──────────────────
spring.application.name=identityCore
server.port=8080

# ─── Database profile ──────────────────
spring.profiles.active=postgres

# ─── SQL Init (seed data) ──────────────────
spring.sql.init.mode=embedded
spring.jpa.defer-datasource-initialization=true

# ─── Session ──────────────────
server.servlet.session.timeout=600s

# ─── Thymeleaf ──────────────────
spring.thymeleaf.cache=false

# ─── Logging ──────────────────
logging.level.root=WARN
logging.level.dev.tharbytes=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/application.log
